# Generated by Django 5.1 on 2024-08-31 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check_pupil",
            name="parent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parrent_check",
                to="base.pupil",
            ),
        ),
    ]
