# Generated by Django 5.1 on 2024-09-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_course_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pupil",
            name="is_active",
        ),
    ]
