# Generated by Django 5.1 on 2024-09-02 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(16)],
                verbose_name="Age",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="username",
            field=models.CharField(max_length=30, unique=True, verbose_name="Username"),
        ),
    ]
