# Generated by Django 5.1 on 2024-09-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="pupil",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Phone number"
            ),
        ),
    ]
