# Generated by Django 5.1 on 2024-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pupil",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
